# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d423e84b7c407f26ab9e9775443508690ea629c905eab9b0a6ad794e593c763c2bd1f2e616f4f1ce2677d388bf266252b4409d509a55bd623ef18918c88d01e

test:
  secret_key_base: 9a2bc317d2ae595c5d40126c2c3c27812b73a6bf25c4d43c62159dac808d0d423dd61b34b9c432f0a39eae867f08c43eabfbd0922fab74785bbe976eb2eb8202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
